[
  "modern minimalist residence with floor-to-ceiling windows",
  "sustainable office building with green roof",
  "historic brownstone renovation in urban setting",
  "luxury penthouse interior with custom finishes",
  "innovative co-working space design",
  "high-end retail storefront architecture",
  "residential skyscraper with panoramic views",
  "adaptive reuse industrial loft conversion",
  "scandinavian-inspired home interior",
  "biophilic design corporate headquarters",
  "mixed-use development urban planning",
  "solar-powered eco-friendly residence",
  "mid-century modern home restoration",
  "high-tech smart home automation design",
  "resort-style backyard landscape architecture",
  "contemporary art gallery space",
  "modular prefab housing prototype",
  "accessible universal design residence",
  "luxury hotel lobby interior design",
  "rooftop garden urban oasis design"
]